<a href="https://colab.research.google.com/github/younzk/rookie-projects/blob/main/%5BNumpy%5D%2001_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.1 Numpy Array

- 넘파이는 수치해석용 파이썬 패키지이다.  
- 다차원의 배열 자료구조 클래스인 ndarray 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다.  

## 1차원 배열 만들기

넘파이의 array 함수에 리스트를 넣으면 배열로 변환해준다.

In [ ]:
import numpy as np
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Vectorized operation (벡터화 연산)

일반적으로 리스트 내 원소의 값을 2배 한다면 다음과 같이 for 반복문으로 구현할 수 있다.

In [ ]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = [i*2 for i in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
#일반적인 리스트에 벡터화 연산으로 곱셈을 하면 값이 2배가 되지 않고 객체 크기가 증가한다.
2 * data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

그런데 벡터화 연산을 사용하면 for 반복문 없이 한번의 연산으로 가능하고, 계산 속도도 반복문보다 빠르다

In [ ]:
x = np.array(data)

2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

그래서 바로 수학 연산을 간단하게 사용할 수 있다.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a+b*2

array([21, 42, 63])

In [ ]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

## 2차원 배열 만들기
- 리스트의 리스트(list of list)를 사용하면 2차원 배열을 생성할 수 있다.
- 안쪽 리스트의 길이는 열의 수(가로 크기), 바깥쪽 리스트의 길이는 행의 수(세로 크기)가 된다.

In [ ]:
c = np.array([[0, 1, 2], [3, 4, 5]]) #2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

2차원 배열의 행과 열의 갯수 
- 행의 갯수 : len(c)
- 열의 갯수 : len(c[0])

In [ ]:
len(c), len(c[0])

(2, 3)

### Practice 01

In [ ]:
k = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
k

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열 만들기
- 리스트의 리스트의 리스트를 이용한다.

In [ ]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

3차원 배열의 깊이, 행, 열
- 3차원 배열의 깊이 : len(d)
- 3차원 배열의 행 : len(d[0])
- 3차원 배열의 열 : len(d[0][0])

In [ ]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기  
배열의 차원 및 크기를 구하는 더 좋은 방법은 배열의 ndim 속성과 shape 속성을 이용하는 것이다.
- ndim : 배열의 차원
- shape : 배열의 크기

In [ ]:
a = np.array([1, 2, 3])
print(a.ndim) #1차원
print(a.shape) #3열

1
(3,)


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim) #2차원
print(a.shape) #2행 3열

2
(2, 3)


## 배열 인덱싱  
- 1차원 배열의 인덱싱 : 리스트와 동일
- 다차원 배열의 인덱싱 : ','를 사용하여 접근

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0, 0]) #첫번째 행의 첫번째 열
print(a[0, 1]) #첫번째 행의 두번째 열
print(a[1, 2]) #두번째 행의 세번째 열

0
1
5


## 배열 슬라이싱
- 일반적인 파이썬 슬라이싱과 comma(,)를 함께 사용

In [ ]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[:, 1] # 두 번째 열 전체

array([1, 5])

In [ ]:
a[:1, :2] # 첫 번째 행, 첫번째 두번째 열

array([[0, 1]])

## Practice 02

In [ ]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [ ]:
m[1,2], m[2, -1]

(7, 14)

In [ ]:
m[1, 1:3], m[1:3, 2]

(array([6, 7]), array([ 7, 12]))

In [ ]:
m[0:2, -2:]

array([[3, 4],
       [8, 9]])

## Array Indexing(배열 인덱싱)
(1) Boolean (불리언 배열 방식)
- 인덱스 배열의 원소가 True, False 로만 구성  
- 인덱스 크기가 원래 ndarray 객체의 크기와 같아야 함

(2) 정수 배열 방식
- 인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가리키는 인덱스 정수
- 배열 인덱스와 원래의 배열 크기와 달라도 상관 없음

In [ ]:
# 불리언 배열 방식
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
# 정수 배열 인덱싱
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [ ]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3])
a[idx]

array([11, 11, 11, 22, 22, 22, 33, 33, 33, 44, 44])

다차원 배열에서의 배열 인덱싱

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[:, [False, True, True, False]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## Practice 03

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [ ]:
#1
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
#2
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
#3
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])