<a href="https://colab.research.google.com/github/younzk/rookie-projects/blob/main/%5BNumpy%5D%2005_Random_Number_and_Counting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.5 Random Number and Counting(난수 발생과 카운팅)

##시드 설정하기
- seed 함수를 통해 무작위 수를 생성한다.

In [ ]:
import numpy as np
np.random.seed(0)

- 시드 설정 후 random 서브패키지의 rand 함수로 5개의 난수를 생성해 보자.
- rand 함수는 0과 1 사이의 난수를 발생시키는 함수로 인수로 받은 숫자 횟수만큼 난수를 발생시킨다.

In [ ]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

##데이터의 순서 바꾸기 : shuffle함수 사용
- 사용 시 변수의 값이 바뀌게 된다.

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

##데이터 샘플링(Sampling) : choice 함수 사용
- 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 또는 샘플링(Sampling)이라고 한다. 

- numpy.random.choice(a, size = None, replace = True, p = None)
- choice함수가 갖는 인수는 다음과 같다.  

 1) a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성  
 2) size : 정수, 샘플 숫자  
 3) replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능  
4) p : 배열, 각 데이터가 선택될 수 있는 확률  

In [ ]:
np.random.choice(5, 5, replace = False) #shuffle 명령과 같다.

array([0, 4, 2, 1, 3])

In [ ]:
np.random.choice(5, 3, replace = False) #3개만 선택

array([4, 2, 3])

In [ ]:
np.random.choice(3, 3, replace = False) #앞의 숫자 갯수 중에서 몇 개 선택 

array([2, 1, 0])

In [ ]:
np.random.choice(5, 10) #3개 숫자 중 반복해서 10개 선택

array([2, 4, 3, 3, 2, 4, 2, 0, 0, 4])

In [ ]:
np.random.choice(2, 10)

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 0])

In [ ]:
np.random.choice(5, 10, p = [0.1, 0, 0.3, 0.6, 0]) #선택 확률을 다르게 해서 10개 선택

array([2, 3, 3, 0, 3, 3, 2, 2, 2, 2])

##난수 생성
- rand : 0부터 1사이의 균일 확률로 실수 난수 생성
- randn : 표준 정규 분포, 기댓값이 0이고 표준 편차가 1인 표준 정규 분포를 따르는 난수 생성
- randint : 균일분포의 정수 난수
  numpy.random.randint(low, high = None, size = None)
  * high를 입력하지 않으면 0과 low 사이의 범위,  
  * high를 입력하면 low와 high 사이의 숫자를 출력한다.  
  * size는 난수의 숫자이다.

In [ ]:
np.random.rand(10)

array([0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676,
       0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559])

In [ ]:
np.random.rand(3, 5)

array([[0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236],
       [0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841],
       [0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358]])

In [ ]:
np.random.randn(10)

array([ 0.92525075, -0.90478616,  1.84369153,  1.52550724, -1.44553558,
        0.37716061, -0.07055723,  0.60415971,  0.472149  ,  0.81991729])

In [ ]:
np.random.randint(10, size = 10) #0부터 10까지의 숫자, 난수는 10개

array([8, 8, 9, 2, 8, 6, 6, 9, 1, 6])

In [ ]:
np.random.randint(10, size = 4) #0부터 10까지의 숫자, 난수는 10개

array([3, 6, 3, 6])

In [ ]:
np.random.randint(10, 20, size = 10) #10부터 20까지의 숫자, 난수는 10개

array([15, 17, 10, 18, 14, 16, 15, 18, 12, 13])

In [ ]:
np. random. randint(10, 20, size = (3, 5)) #10부터 20까지의 숫자로 (3 x 5)크기의 배열

array([[13, 19, 17, 17, 15],
       [11, 12, 12, 18, 11],
       [15, 18, 14, 10, 12]])

##Practice 3. 5. 1
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.

2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [ ]:
np.random.choice(2, 10, replace = True)

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
k = np.random.choice(2, 100, replace = True)
k.mean()

0.45

##Practice 3. 5. 2
가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 10일 동안의 주가를 무작위로 생성하라

In [ ]:
n = 10000
k = np.random.randn(10)
for i in k:
  n = n*(1+(i/100))
  print(f'{round(n)}원')

10002원
10034원
10001원
9999원
10076원
10120원
10038원
9927원
9849원
9849원


##정수 데이터 카운팅
- 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있다.
- unique : 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다.
  - return_counts 인수를 True로 설정하면 각 값을 가진 데이터 갯수도 출력

- uniqe 함수는 데이터가 존재하는 값만 갯수를 센다. 그래서 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않는다.  

 ex) 주사위를 10번 던졌는데 6이 한 번도 나오지 않으면 0으로 세어주지 않음

- 따라서 데이터가 특정 범위 안의 수인 경우에는 bincount함수의 minlenght인수를 설정하여 쓰는 것이 더 편리하다.
- bincount함수는 0부터 minlength -1까지의 숫자에 대해 각각 카운트를 한다. 데이터가 없을 경우 카운트 값이 0이 된다.

In [ ]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts = True) #각 값을 가진 데이터의 갯수도 출력
index, count# a는 2개, b는 2개, c는 1개

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [ ]:
np.bincount([1, 1, 2, 2, 2, 3], minlength= 6) #minlength가 6이므로 0부터 5까지 숫자에 대해 카운트 한다.

array([0, 2, 3, 1, 0, 0])