<a href="https://colab.research.google.com/github/younzk/rookie-projects/blob/main/%5BNumpy%5D%2003_Vectorized_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3.3 Vectorized Operation

##벡터화 연산의 장점
- 반복문 없이 배열의 모든 원소에 대해 반복연산이 가능하다.
- 선형 대수 공식과 동일한 간단한 파이썬 코드를 작성할 수 있다. 

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.all(a == b) # a와 b 배열이 같은가?

False

##스칼라와 벡터/행렬의 곱셈

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## Broadcasting(브로드캐스팅)

- 넘파이에서는 서로 다른 크기를 가진 두 배열의 사칙연산도 지원한다. 
- 차원이 다른 두 배열의 연산도 지원한다.

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
y = np.ones_like(x) #x와 같은 크기의 배열을 1로 채움
y

array([1, 1, 1, 1, 1])

In [ ]:
x+y

array([1, 2, 3, 4, 5])

In [ ]:
x+1 #단순히 x배열에 1을 더해도 [1, 1, 1, 1, 1]로 생각해서 적용한다.

array([1, 2, 3, 4, 5])

In [ ]:
x = np.vstack([range(7)[i:i+3]for i in range (5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [ ]:
y = np.arange(3)
y

array([0, 1, 2])

In [ ]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

##Dimension Reduction(차원 축소 연산)
- n차원 배열의 원소 값을 연산을 통해 n차원보다 작은 차원의 벡터로 나오게 하는 것
- 예) 2차원 배열에 대해 행-평균을 구한 뒤 1차원 벡터로 평균을 출력
- 넘파이는 다음과 같은 차원 축소 연산 명령 혹은 메서드를 지원한다.  
 (1) 최대/최소 : min, max, argmin, argmax  
 (2) 통계 : sum, mean, median, std, var  
  (3) 불리언 : all, any  

In [ ]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
np.sum(x)

10

In [ ]:
x.sum()

10

In [ ]:
x = np.array([1, 3, 2])
x.min(), x.max()

(1, 3)

In [ ]:
x.argmin() #최솟값의 위치

0

In [ ]:
x.argmax() #최댓값의 위치

1

In [ ]:
x.mean()

2.0

In [ ]:
np.median(x)

2.0

In [ ]:
np.all([True, True, False]) #all 에서는 False가 하나라도 있으면 False 출력

False

In [ ]:
np.any([True, False, False]) #any에서는 True가 하나라도 있으면 True 출력

True

In [ ]:
a = np.zeros((100, 100), dtype = np.int)
a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
np.any(a != 0)  #하나라도 0이 아닌게 있나?

False

In [ ]:
np.all( a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [ ]:
((a<=b) & (b <= c)).all()  #a배열의 원소가 b보다 작고, b배열의 원소가 c보다 작은가?

True

###연산의 대상이 2차원 이상인 경우에는 어떤 차원을 계산할 지 axis 인수를 사용하여 지시한다.
- axis = 0 이면 열 연산 (디폴트)
- axis = 1 이면 행 연산


In [ ]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum()

6

In [ ]:
np.sum(x)

6

In [ ]:
x.sum(axis = 0) #열합계

array([3, 3])

In [ ]:
x.sum(axis = 1) #행합계

array([2, 4])

##Practice 3. 3. 1
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
1. 전체의 최댓값  
2. 각 행의 합  
3. 각 행의 최댓값  
4. 각 열의 평균  
5. 각 열의 최솟값  

In [ ]:
k = np.random.randint(100, size = (5, 6))
k

array([[98, 68, 95, 33, 57, 86],
       [36, 80, 91,  7, 14, 95],
       [10, 60, 46, 81, 78, 38],
       [97, 30, 83, 50,  2, 45],
       [ 3, 34, 31, 55, 74, 13]])

In [ ]:
k.max()

98

In [ ]:
k.sum(axis = 1)

array([437, 323, 313, 307, 210])

In [ ]:
k.max(axis = 1)

array([98, 95, 81, 97, 74])

In [ ]:
k.mean(axis = 0)

array([48.8, 54.4, 69.2, 45.2, 45. , 55.4])

In [ ]:
k.min(axis = 0)

array([ 3, 30, 31,  7,  2, 13])

##정렬
- sort 함수나 메서드를 사용하여 배열 내 원소를 크기에 따라 정렬한다.
- 2차원 이상의 경우  
  axis = 0 : 행을 정렬  
 axis = 1 : 열을 정렬  
 디폴트 -1 : 가장 안쪽(나중)의 차원 정렬

In [ ]:
a = np.array([[4, 3, 5, 7],
[1, 12, 11, 9],
[2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

## Inf 와 NaN
- np.inf (infinity) - 무한대
- np.nan (not a number) - 정의할 수 없음

In [ ]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

## 배열 생성
- zeros : 0으로 초기화 된 배열
- ones : 1로 초기화 된 배열
- zeros_like, ones_like : 이미 있는 배열과 같은 크기의 배열로 생성
- empty : 배열을 생성만 하고 특정 값으로 초기와 하지 않음.
- arange : NumPy 버전 range
- linspace, lognspace : 선형 구간 또는 로그 구간을 지정한 구간 수 만큼 분할한다.

In [ ]:
#크기가 정해져 있고 모든 값이 0인 배열을 생성

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
#크기를 나타내는 튜플로 다차원 배열 생성

b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype으로 해당 원소의 자료형을 지정할 수 있다.

c = np.zeros(5, dtype = "i")
c

array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
# 1로 초기화 된 배열 생성

e = np.ones((2, 3, 4), dtype = "i8") #3차원 배열 생성
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
#zero_like, ones_like

f = np.ones_like(b, dtype = "f") #b는 (2, 3)크기를 가진 배열이었다.
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [ ]:
g = np.empty((4, 3))
g

array([[1.98581663e-316, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.60952352e-072],
       [4.96299791e-090, 4.01519931e-057, 2.32529919e-057],
       [1.18995396e-075, 3.99910963e+252, 1.46030983e-319]])

In [ ]:
np.arange(10) #0, 1, 2 .. 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, 3) #(시작, 끝(포함X), 단계)

array([2, 5, 8])

In [ ]:
np.linspace(0, 100, 5) #시작, 끝, 구간 갯수

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## Transpose (전치 연산)
- 행과 열을 바꾸는 작업
- T속성으로 구한다.

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Reshape (배열의 크기 변형)
- 배열 내부 데이터는 보존하고 형태만 바꾼다.
- 사용하는 원소의 개수가 정해져 있어서 reshape 명령 튜플 원소 중 하나는 -1로 대체할 수 있다.
- 다차원 배열을 1차원으로 만들기 위해서 flatten이나 ravel 메서드를 이용한다.
- 같은 배열에 대해 차원만 1차원 증가하는 경우는 newaxis를 이용한다.

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]]) #2 x 3 array
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = c.reshape(3, 2) # 3 x 2 array
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d = c.reshape(3, -1) # 튜플 원소 중 하나는 -1이라는 숫자로 대체할 수 있다.(자동으로 2로 생성됨)
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d.flatten() #1차원으로 생성

array([1, 2, 3, 4, 5, 6])

In [ ]:
d.ravel() #1차원으로 생성

array([1, 2, 3, 4, 5, 6])

In [ ]:
d[:, np.newaxis] #같은 데이터를 갖고 있지만 3차원이 됨

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

## Concatenate (배열 연결)
- hstack : 행의 수(세로)가 같은 두 개 이상의 배열을 옆으로 연결, 연결할 배열은 하나의 리스트에 담는다.
- vstack : 열의 수(가로)가 같은 두 개 이상의 배열을 위 아래로 연결, 연결할 배열은 하나의 리스트에 담는다.
- dstack : 깊이(depth) 방향으로 배열, 가장 안쪽의 원소의 차원이 증가한다.
- stack : 사용자가 원하는 방향으로 차원을 증가시킨다.
- r_ : hstack과 비슷하게 배열을 좌우로 연결
- c_ : 배열의 차원 증가시킨 후 좌우로 연결, 만약 1차원 배열끼리 연결하면 2차원 배열이 된다.
- tile : 동일한 배열을 반복하여 연결

In [ ]:
#hstack
a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack([a1, a2]) #a1, a2 배열을 하나의 리스트에 담아 hstack을 사용

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [ ]:
#vstack
b1 = np.ones((2, 3))
b2 = np.zeros((3, 3))
np.vstack([b1, b2]) #a1, a2 배열을 하나의 리스트에 담아 vstack을 사용

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#dstack
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
(np.dstack([c1, c2])).shape #c1, c2 모두 (3, 4) 크기의 배열이었는데 dstack 후 (3, 4, 2)로 가장 안쪽의 차원이 하나 증가했다.

(3, 4, 2)

In [ ]:
#stack axis = 0일 때 (3, 4) -> (2, 3, 4)로 첫 번째 차원이 증가
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
#stack axis = 1일 때 (3, 4) -> (3, 2, 4)로 두 번째 차원이 증가
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [ ]:
#stack axis = 2일 때 (3, 4) -> (3, 4, 2)로 두 번째 차원이 증가 = dstack과 동일
c = np.stack([c1, c2], axis = 2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
#r_ 메서드 = hstack과 비슷하게 배열을 좌우로 연결
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [ ]:
#c_ 메서드 = 배열의 차원 증가시킨 후 좌우로 연결 
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2) #a를 2번 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, (3, 2)) #a를 2번 연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### Practice 01
- 다음 배열을 만들어 보시오.

array([[   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [  10.,   20.,   30.,   40.,   50.],  
       [  60.,   70.,   80.,   90.,  100.],  
       [ 110.,  120.,  130.,  140.,  150.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [   0.,    0.,    0.,    1.,    1.],  
       [  10.,   20.,   30.,   40.,   50.],  
       [  60.,   70.,   80.,   90.,  100.],  
       [ 110.,  120.,  130.,  140.,  150.]]) 

In [ ]:
a0 = np.zeros(3)
a1 = np.ones(2)
a = np.hstack([a0, a1])
a = np.vstack([a, a, a])
a

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [ ]:
b0 = np.arange(10, 160, 10)
b = b0.reshape(3, 5)

In [ ]:
c = np.vstack([a, b])
c

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
np.tile(c, (2, 1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 2차원 그리드 포인트 생성
- 그리드 포인트(grid point) : 변수가 2개인 2차원 함수의 그래프에서(x, y) 좌표값의 쌍
- meshgrid : 사각형 영역을 구성하는 가로축의 점들과 세로축의 점들을 나타내는 두 벡터를 인수로 받아 사각형 영역을 이루는 조합을 출력한다.

In [ ]:
x = np.arange(3)
x

array([0, 1, 2])

In [ ]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [ ]:
X, Y = np.meshgrid(x, y)

In [ ]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [ ]:
#그리드 포인트를 (X, Y) 값으로 출력
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]